// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKp3E1zTK6vJleFH2xSE2rUzVa82mqUZM',
    appId: '1:335854281783:web:0c8afcce29f0fe3d5b8bb2',
    messagingSenderId: '335854281783',
    projectId: 'vetconnect-3003a',
    authDomain: 'vetconnect-3003a.firebaseapp.com',
    storageBucket: 'vetconnect-3003a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCKYMgJ8Tz-kqvW8dD0SoL-Q7FiuRlQOg',
    appId: '1:335854281783:android:e180a085623b8e185b8bb2',
    messagingSenderId: '335854281783',
    projectId: 'vetconnect-3003a',
    storageBucket: 'vetconnect-3003a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTGMhKqb0dHr1UkFozB8x-uBeH0KubBjM',
    appId: '1:335854281783:ios:aabae5bfedd1a3835b8bb2',
    messagingSenderId: '335854281783',
    projectId: 'vetconnect-3003a',
    storageBucket: 'vetconnect-3003a.firebasestorage.app',
    iosBundleId: 'com.example.vetconnectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTGMhKqb0dHr1UkFozB8x-uBeH0KubBjM',
    appId: '1:335854281783:ios:aabae5bfedd1a3835b8bb2',
    messagingSenderId: '335854281783',
    projectId: 'vetconnect-3003a',
    storageBucket: 'vetconnect-3003a.firebasestorage.app',
    iosBundleId: 'com.example.vetconnectapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKp3E1zTK6vJleFH2xSE2rUzVa82mqUZM',
    appId: '1:335854281783:web:8d608748be85bac45b8bb2',
    messagingSenderId: '335854281783',
    projectId: 'vetconnect-3003a',
    authDomain: 'vetconnect-3003a.firebaseapp.com',
    storageBucket: 'vetconnect-3003a.firebasestorage.app',
  );

}